/**
 @file helpwindow.h
 @author David Hudak
 @brief File contains headers of class HelpWindow which contains dialog window for help. Mostly generated by Qt Creator.
 */

#ifndef HELPWINDOW_H
#define HELPWINDOW_H

#include <QDialog>

namespace Ui {
class HelpWindow;
}

/**
  * @brief The HelpWindow class mostly generated by Qt Creator
**/
class HelpWindow : public QDialog
{
    Q_OBJECT

public:
    explicit HelpWindow(QWidget *parent = nullptr);
    ~HelpWindow();

private:
    Ui::HelpWindow *ui;
};

#endif // HELPWINDOW_H
